// AUTO-GENERATED by spikes/s2-ext-host/gen-context-keys.mjs — DO NOT EDIT BY HAND.
// Source of truth: 上游 SillyBunny public/scripts/st-context.js（只读）
// Measured: 2026-09-11T14:18:26.949Z  |  top-level keys = 157  |  spread elements = 0

/** Lifecycle kind of a getContext() member. */
export type ContextKeyKind = 'value' | 'getter' | 'method';

/** Group bucket derived for coverage reporting. */
export type ContextKeyGroup =
	| 'chat-state'
	| 'events'
	| 'generation'
	| 'injection-meta'
	| 'other';

export interface ContextKey {
	/** Top-level property name exactly as exported by getContext(). */
	readonly name: string;
	readonly kind: ContextKeyKind;
	readonly group: ContextKeyGroup;
}

/** Total getContext() top-level keys measured by AST (spec said 155; see REPORT.md). */
export const TOTAL_KEYS = 157;

/** The four groups the gate refers to as "核心四组". */
export const CORE_GROUPS: readonly ContextKeyGroup[] = ["chat-state","events","generation","injection-meta"];

/** Full key table. Order follows the upstream source. */
export const CONTEXT_KEYS: readonly ContextKey[] = [
	{
		"name": "accountStorage",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "chat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "characters",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "groups",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "name1",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "name2",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "userAvatar",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "characterId",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "groupId",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "chatId",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "getCurrentChatId",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "getRequestHeaders",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "reloadCurrentChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "renameChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "closeCurrentChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "saveSettingsDebounced",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "onlineStatus",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "maxContext",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "chatMetadata",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "saveMetadataDebounced",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "streamingProcessor",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "eventSource",
		"kind": "value",
		"group": "events"
	},
	{
		"name": "eventTypes",
		"kind": "value",
		"group": "events"
	},
	{
		"name": "addOneMessage",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "deleteLastMessage",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "deleteMessage",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "generate",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "sendStreamingRequest",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "sendGenerationRequest",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "stopGeneration",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "tokenizers",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "getTextTokens",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "getTokenCount",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "getTokenCountAsync",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "extensionPrompts",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "setExtensionPrompt",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "updateChatMetadata",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "saveChat",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "openCharacterChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "openGroupChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "saveMetadata",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "sendSystemMessage",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "activateSendButtons",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "deactivateSendButtons",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "saveReply",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "substituteParams",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "substituteParamsExtended",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "SlashCommandParser",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "SlashCommand",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "SlashCommandArgument",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "SlashCommandNamedArgument",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "SlashCommandEnumValue",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "ARGUMENT_TYPE",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "executeSlashCommandsWithOptions",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "registerSlashCommand",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "executeSlashCommands",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "timestampToMoment",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "registerHelper",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "registerMacro",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "unregisterMacro",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "registerFunctionTool",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "unregisterFunctionTool",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "isToolCallingSupported",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "canPerformToolCalls",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "ToolManager",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "registerDebugFunction",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "renderExtensionTemplate",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "renderExtensionTemplateAsync",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "registerDataBankScraper",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "callPopup",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "callGenericPopup",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "showLoader",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "hideLoader",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "mainApi",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "extensionSettings",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "vectors",
		"kind": "getter",
		"group": "other"
	},
	{
		"name": "rag",
		"kind": "getter",
		"group": "other"
	},
	{
		"name": "ModuleWorkerWrapper",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getTokenizerModel",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "generateQuietPrompt",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "generateRaw",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "generateRawData",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "writeExtensionField",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "writeExtensionFieldBulk",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getThumbnailUrl",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "selectCharacterById",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "messageFormatting",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "shouldSendOnEnter",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "isMobile",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "t",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "translate",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getCurrentLocale",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "addLocaleData",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "tags",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "tagMap",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "menuType",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "createCharacterData",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "event_types",
		"kind": "value",
		"group": "events"
	},
	{
		"name": "Popup",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "POPUP_TYPE",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "POPUP_RESULT",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "promptManager",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "chatCompletionSettings",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "textCompletionSettings",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "powerUserSettings",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "worldInfoSettings",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getCharacters",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "getOneCharacter",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "getCharacterCardFields",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "getCharacterSource",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "importFromExternalUrl",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "importTags",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "uuidv4",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "humanizedDateTime",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "updateMessageBlock",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "updateMessageMetaBadges",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "updateMessageTokenAccounting",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "redisplayChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "showMoreMessages",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "showNewerMessages",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "appendMediaToMessage",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "ensureMessageMediaIsArray",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getMediaDisplay",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getMediaIndex",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "scrollChatToBottom",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "scrollOnMediaLoad",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "macros",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "loader",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "swipe",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "variables",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "loadWorldInfo",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "createWorldInfoEntry",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "saveWorldInfo",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "reloadWorldInfoEditor",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "updateWorldInfoList",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "convertCharacterBook",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getWorldInfoPrompt",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getWorldInfoNames",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "CONNECT_API_MAP",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "getTextGenServer",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "extractMessageFromData",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "getPresetManager",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getChatCompletionModel",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "printMessages",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "clearChat",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "ChatCompletionService",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "TextCompletionService",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "ConnectionManagerRequestService",
		"kind": "value",
		"group": "generation"
	},
	{
		"name": "updateReasoningUI",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "parseReasoningFromString",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "getReasoningTemplateByName",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "unshallowCharacter",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "unshallowGroupMembers",
		"kind": "value",
		"group": "chat-state"
	},
	{
		"name": "getExtensionManifest",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "openThirdPartyExtensionMenu",
		"kind": "value",
		"group": "injection-meta"
	},
	{
		"name": "symbols",
		"kind": "value",
		"group": "other"
	},
	{
		"name": "constants",
		"kind": "value",
		"group": "other"
	}
] as const;

/** Convenience: just the names. */
export const CONTEXT_KEY_NAMES: readonly string[] = CONTEXT_KEYS.map((k) => k.name);

/** Keys belonging to the core four groups. */
export const CORE_KEYS: readonly ContextKey[] = CONTEXT_KEYS.filter((k) =>
	CORE_GROUPS.includes(k.group)
);
